# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-lockscreen-player-patch

# >> macros
BuildArch: armv7hl
# << macros

Summary:    Lockscreen player controls
Version:    0.0.1
Release:    1
Group:      Qt/Qt
License:    TODO
Source0:    %{name}-%{version}.tar.bz2
Requires:   patchmanager
Requires:   sailfish-version >= 1.1.0
Requires:   sailfish-version < 1.1.1

%description
Lockscreen player controls


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/patchmanager/patches/sailfishos-lockscreen-player-patch
cp -r patch/* %{buildroot}/usr/share/patchmanager/patches/sailfishos-lockscreen-player-patch
mkdir -p %{buildroot}/usr/lib/qt5/qml/org/coderus/mpris
cp -r org/* %{buildroot}/usr/lib/qt5/qml/org
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/patchmanager/patches/sailfishos-lockscreen-player-patch
%{_libdir}/qt5/qml/org/coderus/mpris
# >> files
# << files
